"""
FIFO cost-basis engine for capital gains calculations.

Implements Art. 37.2 Ley 35/2006 IRPF: when transferring homogeneous securities,
the ones acquired first are considered transferred first (FIFO).
"""

from __future__ import annotations

from collections import defaultdict, deque
from decimal import Decimal

from renta.etfs.models import CapitalGainEvent, Lot, Transaction
from renta.utils.exceptions import NegativeStockError


class FifoEngine:
    """
    Stateful FIFO processor. Feed transactions in chronological order via process().
    One FifoEngine instance should be used per ISIN group or for all ISINs together.
    """

    def __init__(self) -> None:
        self._lots: dict[str, deque[Lot]] = defaultdict(deque)

    def process(self, transactions: list[Transaction]) -> list[CapitalGainEvent]:
        """
        Process all transactions in the order provided (must be chronological).
        Returns all capital gain/loss events generated by sale transactions.
        """
        events: list[CapitalGainEvent] = []
        for tx in transactions:
            if tx.is_purchase:
                self._register_purchase(tx)
            elif tx.is_sale:
                events.extend(self._process_sale(tx))
        return events

    def remaining_lots(self) -> dict[str, list[Lot]]:
        """Open positions at the end of processing (for auditing and carry-forward)."""
        return {isin: list(lots) for isin, lots in self._lots.items() if lots}

    def _register_purchase(self, tx: Transaction) -> None:
        unit_cost = tx.abs_total_eur / tx.abs_quantity
        lot = Lot(
            date=tx.date,
            isin=tx.isin,
            quantity=tx.abs_quantity,
            unit_cost_eur=unit_cost,
        )
        self._lots[tx.isin].append(lot)

    def _process_sale(self, tx: Transaction) -> list[CapitalGainEvent]:
        lots = self._lots[tx.isin]
        if not lots:
            raise NegativeStockError(
                f"No lots available for ISIN {tx.isin} on {tx.date} "
                f"(attempted to sell {tx.abs_quantity} shares)"
            )

        events: list[CapitalGainEvent] = []
        shares_remaining = tx.abs_quantity
        total_proceeds = tx.abs_total_eur

        while shares_remaining > Decimal("0"):
            if not lots:
                raise NegativeStockError(
                    f"Ran out of lots for ISIN {tx.isin} while processing sale on {tx.date}. "
                    f"Still need to allocate {shares_remaining} shares."
                )

            lot = lots[0]
            shares_from_lot = min(lot.quantity, shares_remaining)

            # Proportional proceeds for this lot fraction
            fraction = shares_from_lot / tx.abs_quantity
            transfer_value = total_proceeds * fraction

            # Acquisition value: unit cost × shares consumed from this lot
            acquisition_value = lot.unit_cost_eur * shares_from_lot

            capital_gain = transfer_value - acquisition_value

            events.append(
                CapitalGainEvent(
                    isin=tx.isin,
                    product=tx.product,
                    acquisition_date=lot.date,
                    transfer_date=tx.date,
                    quantity=shares_from_lot,
                    acquisition_value=acquisition_value,
                    transfer_value=transfer_value,
                    capital_gain=capital_gain,
                )
            )

            shares_remaining -= shares_from_lot

            if shares_from_lot == lot.quantity:
                lots.popleft()
            else:
                # Partial consumption: replace lot with the residual
                lots[0] = Lot(
                    date=lot.date,
                    isin=lot.isin,
                    quantity=lot.quantity - shares_from_lot,
                    unit_cost_eur=lot.unit_cost_eur,
                )

        return events
